# Generated by Django 4.2.2 on 2023-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agent_pic', models.ImageField(upload_to='agent_pics')),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='property_images/')),
                ('house_address', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('amount', models.IntegerField(blank=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True)),
                ('baths', models.IntegerField(blank=True)),
                ('garages', models.IntegerField(blank=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ('name',),
            },
        ),
    ]
